export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"

export const AUTH_ERROR = "AUTH_ERROR"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const SET_ERROR = "SET_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"



export const TASKS_LOADING = "TASKS_LOADING"
export const TASKS_LOADED = "TASKS_LOADED"
export const TASKS_CREATED = "TASKS_CREATED"
export const TASKS_DELETED = "TASKS_DELETED"
export const TASKS_CLEAN = "TASKS_CLEAN"
export const TASK_UPDATED = "TASK_UPDATED"


export const TRANSACTION_LOADING = "TRANSACTION_LOADING"
export const TRANSACTION_LOADED = "TRANSACTION_LOADED"
export const ADD_INCOME = "ADD_INCOME"
export const ADD_OUTCOME = "ADD_OUTCOME"
export const DELETE_OUTCOME = "DELETE_OUTCOME"
export const DELETE_INCOME = "DELETE_INCOME"